/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Contribution = IDL.Record({
  'address' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const Allocation = IDL.Record({
  'address' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContributionsForAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Contribution)],
      ['query'],
    ),
  'getAllContributors' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
  'getPresaleStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'active' : IDL.Bool,
          'totalIcp' : IDL.Nat,
          'remainingIcp' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTotalAllocation' : IDL.Func([IDL.Text], [Allocation], ['query']),
  'updatePresaleProgress' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Contribution = IDL.Record({
    'address' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const Allocation = IDL.Record({ 'address' : IDL.Text, 'amount' : IDL.Nat });
  
  return IDL.Service({
    'getAllContributionsForAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Contribution)],
        ['query'],
      ),
    'getAllContributors' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
    'getPresaleStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'active' : IDL.Bool,
            'totalIcp' : IDL.Nat,
            'remainingIcp' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTotalAllocation' : IDL.Func([IDL.Text], [Allocation], ['query']),
    'updatePresaleProgress' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };