/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Allocation { 'address' : string, 'amount' : bigint }
export interface Contribution {
  'address' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllContributionsForAddress' : ActorMethod<[string], Array<Contribution>>,
  'getAllContributors' : ActorMethod<[], Array<Contribution>>,
  'getPresaleStatus' : ActorMethod<
    [],
    { 'active' : boolean, 'totalIcp' : bigint, 'remainingIcp' : bigint }
  >,
  'getTotalAllocation' : ActorMethod<[string], Allocation>,
  'updatePresaleProgress' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];